### PR TITLE
Use absolute paths instead of relatives

### PR DESCRIPTION
**Pull request by dolby360**

### CODE REVIEW

**Comment by svmorris** [comment]
The pr and code quality is nice, I just don't understand what the purpose of it is.
With all due respect, in your pr you didn't provide any explanation about why using absolute paths is better than using relative ones, and I don't see any reason to do so.

Could you please explain why you think this is better?

**Comment by dolby360** [comment]
> The pr and code quality is nice, I just don't understand what the purpose of it is. With all due respect, in your pr you didn't provide any explanation about why using absolute paths is better than using relative ones, and I don't see any reason to do so.
> 
> Could you please explain why you think this is better?

You are totally right, I'll add.

**Comment by dolby360** [comment]
> The pr and code quality is nice, I just don't understand what the purpose of it is. With all due respect, in your pr you didn't provide any explanation about why using absolute paths is better than using relative ones, and I don't see any reason to do so.
> 
> Could you please explain why you think this is better?

I hope the commit messages are now descriptive enough.

**Comment by svmorris** [comment]
Alright that makes sense.
What operating system(s) did you test this on?

**Comment by dolby360** [comment]
> Alright that makes sense. What operating system(s) did you test this on?

Win10

**Comment by svmorris** [comment]
Hi,
Sorry for the late response, I was busy with other work. I will test and make sure it works on linux as well, before merging. 
Thanks for your contribution.

**Comment by dolby360** [comment]
That's OK.
I'm just planning more enhancements, if any help required please ask.

בתאריך יום ד׳, 22 בדצמ׳ 2021, 21:42, מאת svmorris ***@***.***

**Pull request merged**
